---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-credentials
  namespace: cloudflare
spec:
  encryptedData:
    token: AgAcgGURQqvzT99da13qOjt4r2lhX0NbDp/PFo3TzWV+PEJEeqzuS9iPirD//tFa1VgO09mfumCarQfPOk1BtmC3Lh2JGIeuchEItPr8Ow3Ij6Az+ITNO3Q6eRl5slY+6Y/ac7j2pOToAeoVus2kJzOx1+7+Kqjm2kbHoDABj0FYIef03tSbQJK5PfYaceEob0SZ4WiOk+wFp5mybE+uw3SVFno5BZqxDRTxaukeeSUD5MjfYw5Sonwhrmr+X2t7valz5CghDqsR5ykSQ8UDbepGVOlNZ91Rtv9IQcBjHBm/63Yee4iwAetI0UaJe46DB97P/tbU9MaNrrK4bCBaaeuXSof+MpsUep6zpwoHDZv9QH3jQEg6fc5X1RR9iJrtle1mveRjazgu90cxsRwB3/aEROoK76gVf7AuEVWIoiaHXUJNNh7dXnsHRPJAgOOnK2Qv7eZSVoQFjB7QJ4yhU0NBeVc8xxcd6DEnE4uob57XUCs6DG9IRtjjD/VWAtfI/5dRZ0qEde2g7549w9XRJ1l3YlyDwGPCfoWKZsk1oVh8fSqIX+P7dsV7ayz4OW9Zv6cMxhMxZpVH9alaMUupGwQmCsKXddtb6sxye0otMPgkBUGJBcr5DPzubIHtaZyuC4+E9b+fOUd9VHmC3R02YowlJwvpmL+jr2eHSe1gr5Zfz53ZJQRZer88qO8s5s+VCTdOQQd8NjrBwboTINqTlJvBX0PelsM00U4fxLPx4fsBMtxfe9EVyoa2+vLqF5CdJgsXiGjHljA7Gp1leMxJUZ8JEYMPxDlPlAt2tmbwXIPK2O6fjcq/nJ0J1b5U9v5YilGRp1MCxEpR7xDmN9YcjwvWwjApiTbSVjPO+spKu8VGR/cW29q5TPX9s1hYAtlIjr2i+YSt40oiWqrmtM1oeSypsM/Z9KvaicxP25VyISeQz7g8U6emSD0W
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-credentials
      namespace: cloudflare
    type: Opaque
