---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    token: AgAdYMCAf/wN5HiNe9+jKbfuBeQsYnliUC06uwC1GtSgXMdlmzIQWODabAXcAgdJxL7naxY169RKphpB4fZhsm1WQIWtMuP5OuR4+ajmtDJSQ/pN6yxFXyvmAZJF6nXq0E6zsVxn7s8sBIEjhU80fZlC7vJZtZ/yaky7BvMcKOh0nmGEzNs0B6SNmHjF5g5JYeNrRwklUpTF1EUInUEPUwwytLboqFEtDiY1Xag+NcYUoWcqmPNKA0gD4B+aVboJGK2u6vSBEhNV1jGmD2lmeiCwkwoeShzJqm0LACyIpvDkqf4eyWJXVpzWqaJTcgfmznVTUripuO+09OTcgz0X9YTxqqXGq7A0a3roEEwThVOeo4Ph7UrdwKkJNJsuPlKx27zNUETcOEmrrslfoMDE6Al6RA9ONq+0Lbv2L01Sj+sc0P8xWA1YsafiJVwXuuJ7fhMRJqoT6+W6zHPG+13QPoJsqIz2di0yOyqyDocyoQkQoAJORKe/WF3BKOBDTzWdXBtEH06MsgvZzdWhywV0r1Avk7VtXBaA8DFvDA1lXho5Rg+Ro3Ty6DX0j3i1dN4JwY5/tnPih4HwiZmC2Z30Ue9J3MxR2jnAB4L2IXTg0OSPZTsHVJB6dUCc1Fq8oBEmIi4wyTr1Q9FO24IH/lwbCq2l8byikUE+2+QIXKRg276nIDT0OI87PtjmVK4dRwF0zB64O16isqNqy6CT42Y2GpYVxsEEd5TWhxma9DdCnDHzcQ9bB8hSnpityK9Vejb8GwfhaVL6Xw==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
