---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    token: AgCAm1SKs2cxNMKvdUIZ1WkzCXUeZs6ZicjIsbqWF7UamNXNx1UNqIWnVCB6f33e3I51bbzcP5EAC7Ma/1IC3dVrZoSAzdC+TZbdQ0Mxz8HKP7Vpk+UAq2vGO3pAlr5jb7g/cJnia2ppARwKR5LRoK+RhFQ+eTBAxvXj8Hs+bGywX6AdedtUixkLEdsZMYnTSfpABYg8zbcWNxPajFChF++JVWvImKYSiagCAIql2XIAOls/l/ikFv308rpRdr7SXj97gnqlahoVT6IiJ/b4pu9qPe6+RggET4fYBAgV7RT09VFSo/IYIhVOfGVQ/8uB9odOCYTM5vc6iPHKP9ICcnPeOo+YNkW0Ry6R8J8nSyrL2sW06QB8NysRm/te+BwXSDmZbzahq72b3+nub2WQeldXkbwlOFGXPXz1cPGO9MBlzbWzNi83UEhJDGzZN8SXKZENTsIwDNXXFZ46ghVZAdpSCtUAay0E4XtzHrlkECawZn/Qukrb9HHXpDqswx2ZMwzqO2NfgpZU8D//JlD8o3eQzuPw1OKyEDH30FaHhIogXzYfiD7hXeRXH6b/PwOtlfAM7KcRobjRRnNlFjSWglhV7FDL08/dH37/Dw6ethZoXt56MP6Fln6MAiwFNcSXJv/2mnj/28iHHM/+1QIniI2YD9bhdHjh7eon5T5lz647LhQTVDiZ8agS4DUp5+F7M5bPU57OZIUJUmSTrzthNjKByju7hL6OZit2plTiRpXtSQS3MuurPh+WLJwVMn3uM9Hkt9mgKajao/yrC7hAxS5cQeeFRH8D114G/guVb71Qh2njZE7u0InsCNquvT7cUkq/ef7b4FJsDLUx+VpLUNn3QW9P3bnHX9TAhqgC3Y+EpUbAiGk75n+CLDY36fs5Ke+/Go/Qbmm/vXsoqr1QxjrigMyjX7NK4NbQsNxm4bMW1g/dQA+hs+2j
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns
    type: Opaque
