---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    token: AgDHWUAQaGopFtCnmKtrya8CVcktFGqvz5pOXo50lmWXfmleO0GF5eL0jIoAa2DhskETJzFXI15ANA0/Tm2V85fUrMx2O/VRbwj+H6v4oIdkD+LuOa1m0IpKIKPvtD1mZ016hiZ6Z2JKysCVVfFGYuQtUYtRw5T+tweLcfGIOIrPlEcSf03as2r1AzrlnYY6FD/8VEBLoR2cUcnlb2gorSFRv7+kUSmJTf2LP7k6Yn+/uNukq5LDNLWPrl5BB6BaLaZniwcYwNUqKXUmkcSgNfb/YwkWx+QHt4xwDVsdX8eXF89GBRtfN71jXRLu0vm1Mzcjb8uS5crJc3rJ5lbPgKQuDPeqD48T31ZsAjIa2G2rZF84g5aRlvyeY7Bmvo828Z+iw/s2bCFbTZwXglDvmUnUBBZQsc0mthWL7rMPxHFQPkXc96/bZVMcDkMIbxT+8Tztr8EC1YBwM+zwycZHl07dMW+srAjCN13uLjWbxuIMeTUJmSlHt9O1GwtmW4zz9srFurQLmHk9Xc4ZpzhH7O0ocf9mx2w7dMn+/l5GRQlRdaaXtFBYYpvGlU5GpCDdAV2nk+eSfABIGCaD2u9JdZPMFhcEs/MUHx3RBu95qp4Q0EXoP9RNrrMEjKlUfTNaX3y33b600kttxML87JAZQZGtWn4QkowJCzVVu7K6xgSm7b4Zg3+J343n1zi2qtB1xVB5t7oe+RmW4pfYQCXvPCSB3ETQ7QOgMZLbq1/1Voaoou+7U1sn8fqmW+T1KdG2B8DMsEuCMQ==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns
    type: Opaque
