---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    token: AgCZpWsAWNjdS6isZNIGU/fe6R4NqT2nBZ7U/jQng+fWZc8ufhMEd3SWHUq4Ov6lWmCXXYcXHSH5eIXzemhw8gmrVD+aCTiQyIY9D8G0oAZcOJUMQK6twTRwK86D+nfRPnr0bjbi6ZkmoFePxXHGtjmf91xwTba8+hTIUxUkp480IbilIQE8THEa7UZwYGq/ADEJjC4ZuQ3SDO2izZBcgpWdSYKoKe0lxtB3uXzzax/6F7qKeGGwKKy63S82IZhDOpwbatqYO5LQ5nXnBd5gbBBLvnH6WuiivI60HT5kqcqmULG7vLO/LJ1V9D56q4No8PA+9R3d0bQJE/o1RP9UQLkBAY+II4w7z7M4ymKsQh5tLmS3MHEvzqKKtIy4K8TIGhNMCPR01BXWq90nfGs1z/0L7MPFbWphCLWPUKnLOPds4ZA0/wQ6mnOcDYcjB0Je+xNXYcIOTizGSq/pHT1TDu3ECFHGjsGlJ5eeCa8j9bhrQx5YNQ4IQHCvB5ckd7et6gcWkD2duC/NE1OvfJ4cw3xawVPUQUFFWSaWmaAo3kei5nWrK0NaGJzY8x1YpYTbLqzj4WrTzhK3qM0NafRwHgdIxBr3c3I1hXpE6XpsXislCldeoTAP6bxIwVXsVH4kRYoD7kZ6ATfoUR2I2s8h9ABEa7s2hev48ta6kQMbCKEWGvHjo2O/YygqH0oVDKn6GQyRQSORuuw3MaoT02E/9klYOi5qCj37UWbKLXMLz4XGqrUKah4ahPkqBLTdAD+Epc8J+vu6Bw==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
