---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-credentials
  namespace: cloudflare
spec:
  encryptedData:
    token: AgBIDAq9crwcPIC3XjNw5X40dva/DjBhAkTSXXHp9Nx/BpWnxTT2rAToUEzdN6jL6T3FFHUG7hqts8gmmcqOUx0oq5RBeDHb/665dyX9gYUgDXMvQJm39KCiWrtjHxgvCOH0i7djZgBhgE85QbCqK6PLMLIRw4TTAJJAX2gQtV0UJ4qVh4gWzbd+G/ZJiNraJeeVp/qx/vYAhnlXe5VCXD9mkBwtlpsuRB19dDK7Y34CRIoqWGH8/etnbwQYwi+KEsi/3yGF6FNZG2gd390QcYSLy0W06Cmj15zPd3RF2KyPDsRyEa5RhWgesTM55+Hj9zpp/fCk5ZW7AkCvkXPD64wfvyYI/pGSE5Pj6a3CcRjkJVOABrDOFh20cbBMOgGvMUTlTt5v/5uJ8MXNtgTSmcVabL+LR8ePoB18N95lz1aRZfZxiQcqNg1pB0/mLnv7DZxx/doROmqIMEgCHxZPPDob7cpP0zSUHFoXIFh5K5ZoyiyXffaKkeHVSk6awdk6plTUDUCXuAe+q7IRPZkITxk7SiLV39Ja8ZFngwcVN3P7FgqiZlraRHGCq0VVzMdSc3KLhUFh+A7F5r/5if/USUOneGqcPh8nzsKT3pVTkSD9ciss+E0cp1LhhfdlWrMkvF3jCYySxv2Lv/7xQpXGwVLgrkgwDAE7um2vzOuuE4GQ6uw8zFe74LLW+2kQxaYnz9iopiEz7tcvAFiPdPd0jDxtAqG8wsEMQMnmN4SbHE91xwlHcAI+0+J/5s8/Y5F7AL+EZFKc9dHNnscGVqgIAcNV7BECL+mcojVy/WakrdYYJ00s5ZU0RWejCYGjbyRWFySnW4A1ksfaDPgVEMpxntMf16E945dsHF3gmamUBwB/4n+79+xH0+8nS6uqmy5OLDSZ/cYuyU1tefTh0RpgdOavL/nQQnsMp38IlXl5Z4KnCTHwlaVqTmgV
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-credentials
      namespace: cloudflare
    type: Opaque
