---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    token: AgAKLxE9WVOj8AUxc91ATHyEXwZzCp3r/rPpDckzl9xSx9GM9aWXiEp5z67hxzQmdPzFx8yck0a5ZXR9CIReGBn3imGjJQpNcgzUmsL/FTGIdpmGIy4ob/o9vDaW5ScsgjfrFDoA6Yu2Bp8rGHB13sGevtQ8WyEsPef0jucSxK8NcpwSgKl92cr1V/FjAKL+7uIt9FCBIQqNe0k7MPndwCrP8KgIqBnFn93JJLQwGTcH+vQ+skyXwd/Jep0Ohs7wUEnnMZVI0R7bFOf0IP6+80YSuQ+AjQ8bodytT6GGoBnVfkryO/4SCjWYwtN1hD2mj5s1KErgjF0069EgTspkwLtS/T6jFfk9gzCFxMuc52U9vk6BzrfGoZ0IAFUBCNTil8XzcB9s7UcczcHiv4LLQUvxk3tGQSdO0I52RBsvTw77n+rJf3cW3ZvqHVvwHHsrAqRRItIHlpFKt95wglxFUv6LH2BFnhJucRftTQ3i59EuetftR2dSSZIFxliJ4fEx1MBjkKwRuDUwmTpaT5mv4CdT6oxrIVMiVZpFA+jG/rZoE+yGTuitIRwfJnAmSxfK2FKyXU4yF8LPlAwEjACSSQMxLEev99chgapOSj+/mTV6jKQYI1/rHq8zhpybtw+73Le10DWE3dL3RHxJzk2z3Edq5j1v+JSHEKl/jNQrAEmHL3eG2fx/NTD1r+heUJ1wa8JbCAym9CFlZtsvbwqhfrwvEwdGqv6D33g6wWbmn/WVJDmLgSBtPW27ya2eq1g5hl6xGY5saQ==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
