---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    token: AgBdMdcFTXAQeOLAnnQqhmidqMI0ilycgXdk1oN56vOrx6NAlw6iXR8JhvoIq6IyqwZo4t6TbqxdxBOXbxtS7YhSBg9Qeg/3eHYGurN47AWTXMM6BY3+XfKUZXq4CPfvpp+gcyMlTHt0qnPrY4X6W7o12kYcmkw1CK70MNs32Noh16KdTH+s013KakanVr8xfXD+EVJ+/J+0tKkPVzqTZWRSqUG/x6S3luZvv7bPusWEYPraN+cVUUXE3OSZxMScfzDESskqNmbYR1mULj0WbnDWdfDmymkS5bmFPZcdhRUb1pS583rWXXukT11UnklsHl1zTIDOnXrva/BBLdKdVgJneJGbS+EWMop2E2/A6zu+LDzly4AJp6rIQcNCv5ebKvEgEreBGInhBhYfIyh8WpiCtHgn4rk1T/fLLwryhZrQ3gTR2GWZklHellPxCcBhT+9+9bpNiFVxz9pKO7g+psE4lZvrS8481g0447RKwy2JiuHPmwSh+qQxqD5/FXM98l5/q96VneJy4+M1jpItWezWSYi5GAoTp1o13d29evBqqk9mOSR0+D//ofkKZZNJwdH5rHqSmFbxjax4hjZ3DRgQXzKSbfkWMGOq2u2YV6UVAAr4qhMwex4U3hAU30ZQJ20QkAEjKqAvsCxNm3rt59FWUSkAsY+ipb3CIvfUK0U79aAnUTNP7AURUmqjDyC58qbNa3N4FyEHRsT16dtL1QwJEWHg7pK8rtt2F/MelFrWuudn+obrsSkSrjqmZ+PFM0nSUcZ5Ag==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns
    type: Opaque
