---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-credentials
  namespace: cloudflare
spec:
  encryptedData:
    token: AgAJplWxPOXS+0SpjFfxFgpvgpItjLJiyzMOrB7Oacr6C+XlILhCR7LOZYfIW8Kq6knt7jl9mDtPfUqXAojhAigkoX1haWukmkJoQUyKw11LEZJ2EbFCRhsfjLt30hVBsN1XH2S+vBy0QR/BvfoTaJH3cYlTq9TUYaLyheXZ9pjYGGq2JapweFGAaIeRDeZRBvuy7QdyBLQ6+sI7Q5MmUSCXU+xgvfI9nXP0HBYfEFr53QGGiBmDZFOx4Lpd82YZo709OxNGcfFGyZZ4TQ0YOT4qrRRVdG0NAU6ibTtOU5xcOinYoEXJIh3UMAD0Wzgr75RNUqpXWR8p1yzC4FSuS/lF8rLkkVOUFB6YGJcXctRlvf22qOaHXS2Q97EaI9P1E8qpIF8L9/lN+q6doDxKBndGmnnB+81RPBL2NMPxcMvV/5tHSnGZlEeSAOaz2EGZk05Ohul+9L1EPJr6x/jsFW/J91hTwUn+/toEsZ+CJa0KCidTJs1wIfm2O0gV7bmNb+9SjPaqz9fohvOPIPQolnlzYZuuJQy96vKV0TwVacgXcjBTUrYTMxzXcAXsuXe9oViDSF2kgW2Gg6Y05kiJfb8T+uqshh9haTWCYr86A9zWZ3DtP3MOVQ2ZRhhdbWjVJJUW4kjPP9FQrtph939VoRTF3mltJ5Z8U2M/zBTJ0aIeicxJ8KoBJmp0xGRAeYA40sDdevdJ0Z6oG9GrPhe/blT9MfRNpJjWYiVgrO5zfSl5A6FudAI7XNbXFlQ8wldCFOXm13RqByADUvXI7K+CfaVoMNWUT9STjqwEsj3UUHelUcW5WM3G9zlaNYjlq+Q/5kAdcS/ysDkDNVdJiISVInPZgjNAszVv0HHtKzTB4PMAZ5hN6l8KXz7WNBLcBDNm9UcD/QUhZCWzyjwOlo/X3XsDFtJfLUJt2dYK0l01/GWXO7D6GhUz8Ft8Ti63MmVA7prIVs7RbhnRriOl0ppPByK20UHok2XWD5ut5GPjLLAZnxehY0XLlg2dsGSvw7woMag=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-credentials
      namespace: cloudflare
    type: Opaque
