---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker-registry-token
  namespace: default
spec:
  encryptedData:
    token: AgAtt8gQ2cv76JXEq/NXUWO1xo78eXZaFSVwGjSL645AzRiNUWQNKCyAumnB5mybVsGBK2lLfeR5yzhi8BkRGkFO6EhFCMoyPsnBsVeGQs5hl9pavXOa+wHMkvhJS7uBLdOwgEZ+LeoPqnOTciIjZYTSVX6Fh5zeJ7VSY+4OGNK2Dluay5rM9W0z7Nrx3C8JDBczFEq8xp49r0dzO57c5p/BziKqz3QGlupbqxK26sUyDlNjetGOwiJJJMpAoKxFsfrlqbg1ZG0dqva8ShFXqoaWfANtqRU8ELSIsQGj233LSeOSdpl6g1KItmp+UeaO5XIwL9EjSgoTAhaTyq0x9or4MXpLj7jmzfOM82L2clzEfC0lAGKYNeBW8GWH96VIXgWoxJVbCanccMpe0Eyli5JgITARoe3rM2vytESeaNyXVpDv4WfqRZDq+0H8M9Yu1e3LRduj8NkOoLavPUKVy5Wa4UNxuvdvOV0HpE7cjmDDCw5J3aAlgr/SzfsvKEFNcbKpFsZrP6pVFkvWGKofMoCaOb8NqYgh7rFLRtH9XYtiRkkEMqS40ESCLnUeRWn0t+6FDGYkoeq7LFugGnaTkS7889NV66vedAt0rRNLohMGYbUeMKq5SVV5VjcBB7q/gctGQbas1i4wyuKhljRjzYO3apYEDKV/qNvXaPOaLcsG0qpBRnYm/1gr0SZhOi25rhUszdzbE6YjLR7KY3zSOleZAIXYZLkw3aU4zyBsAbCtP6d02tM=
  template:
    metadata:
      creationTimestamp: null
      name: docker-registry-token
      namespace: default
    type: Opaque
