---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker-registry-token
  namespace: default
spec:
  encryptedData:
    token: AgCFptbvoZKRGIDbX9LDX4BXKG3GfGbDonp59wtzJ4gspKUBqIfAM5QtHPl22A6hBDctcuX1N0Jqt2QN08dk8vGhTO1PkfcaxYOfvbqNTxFbv5KlPC7pWGZ505N4kOS1StztzOSYq2bWHQYgDMSkNirpjjw0jhmZqa3Mz/erus04Yemgyt0GeU4MagcZeQO9MwbTILaVjRigxN8tsp1TUgdTVdqp601AeY+amVb9HSs/Wn5xOJmA2ECW5j9jrEok+1BTlq8nSwSA+bJEblhSepaHY2shPoRAW4PWnxMJG1b8M+UTjiiePpyIxm5nJj6DWKjwB0aYS1j7F0/gXp3ZE0n11UlbuRxrwCxonMAan3ZRI4xMv4uhJrBUzMhE00rQBzI0GTP8cvm+6WRzxY7F5IobNnf9xp4rSwwDh4SLEDOkpZn6N0RVEqa2NCj+zz7tnPv+B5sKIISxmK8guWDYREmKB4ntQTZ4CWnsE38qzBnkq/pA0Ypncbu633D8uyHmYRsjxsN7opQc2Iau2K7UHKOxn35h4BmxhOSRAfuoHY8Hn9kwDsR/QbDPjj0cK29puQvNh+QzYXPoi08iJ2n67SMtPYFIU1zhkR7g3pl1MJMaZy0PIOJP9e8lxDyxDDixyFNLuLO5VGYWvw+hjqHAkbGFAH6peXc9FNYTIZQj9/oTVO57ufmsHkr4t9sG/dvzc4l3P8ON0fwcb2OoBDbFhsYxbQA3bcfwTlBtedRrdVAcBqT0emI=
  template:
    metadata:
      creationTimestamp: null
      name: docker-registry-token
      namespace: default
    type: Opaque
