---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker-registry-token
  namespace: default
spec:
  encryptedData:
    token: AgCZmey0E6yp6r+EIbpc6TB012rlFiXXe/XIGaLF0soM0Enp6sCIj4CRmPfUmtwwcR1Vw4Oqz4wUn1z9eU38H2IYFFexhlivYYJaAA360G2SKS8rk+m8TXj8n5Bw5mqLy6SuHCpNtFblXq2nMd07KJ1+RPX2GyCuHWsCW9jXa5a99RRjDONBVkjrcsqzo39ZyU9DbqjVvU23JSIr0n4KgLyz2rzIm6Cm7GxtWyG+ElvAs3QVxrCAzZ0cw9/fmQ9FSlW0YgnOwsHKCW3kMl3xlcuCPZmLRGhieIybP8YTqPFUffPlst9yipoyrEsJffDP7R5kYBwborLUJCcbicUOM+OhPsCLf+gej4Hv9YgrDtrQtSE+VJih622xP6MX+h4+8QB9ehkHjSQW3Qefbw1YX6zR6PkgnbiHpX7u0yrOsduattr6rNgtr/Gha3CnBWGzU8p9uUCuF4jT/8tRHG68yaFS5bHcaP4Up/rDC77gsvj2qe9o/znntgWs2BhuqKLeGhXu6AtbRciSCqyXJm6pxM/Aaa+wwRpcle8cXOXhhbdSCts3Q+nj5uy4zfGTeSJ+W33etoMhSQR1QBygiwvVyuhwT+d7zyR4JB6sWSyXtHKPKQFRz0PXrB4HI+6c6U+i+w3wuzL5TYGGhtVTgC0epTdnSoPIoMVzUVT2M+SnMI6xIYGoC4D0TzIHgrsKY0L51ln5wIBdw3APyV+bwXAxh84EMdr4Lj8fJJTOVLN9HfTIDQJZ3rw=
  template:
    metadata:
      creationTimestamp: null
      name: docker-registry-token
      namespace: default
    type: Opaque
