---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oidc-azure-clientsecret
  namespace: argocd
spec:
  encryptedData:
    oidc.azure.allowedAudiences: AgDLXSeTUdU8WB8J4PUODV29L8Zeg3t73oOV1O588teeYNfhz3+SQPv7Pl7oL/RdAtg7ysaRN7BAed6Lhg9aMQqbejdWIMfXX5ZkvDfEl6sXO4UAuiUuAIwMzShceuQuH2GfUJOA7h4ef6prkQ7L/fOm/RbiubBSfObBhC4SnsPl9wSRwFFEretzOzSoKc59ItqW3ptSYtpHLNguV/AFj8ENrKOqQKPxl66MULU+bWVquDq6f5IPyq3YEqVFYTcyBxrXM+/lsUi5dAiSLEQU5AoCOB4f/rflG56SSujt1wIuvM/TTUyeKzhY4dm8Yy0VO/ewcMdbzRj5ojyaRrjr+UfCmcXaCrbBGWIpuQYm2HSaQVUYhm3oahJbO9RXuBoFeZ4uwsvDpULd7VHuRn50VAtZZ24+WIkZ0jSLs/Drwry91EHfnvefxXBl6MEdJZLc5hT9mHvgzHu3pFfJPlRnX6LjxXFE3fCSkKxM3vSJj7ertaU9c0rty60/e6mwaZPAbOd3NSQaLz0CbIBy+zW0NAEpKAEEgLDXvyR8KE4RhCR9QQD2yfEYbeUpDrg2M5TsjwVM02nwOjB7Wg0S4tNxc2d9vmXEBO89lecDX8Q2ZylFe4w6yEkrQ7SpwTVAs/vK2BIiiI+W5SAzQYbk8piYiq1Mc+5jeJNqsg1gszAiUvhQAkRHl9vk8NWxfIbVZMjOi+YvjGvLCSq5JgBa0KxXqz/UuaP/BZlH6fmw59j8/tCyqHCpDFc=
    oidc.azure.clientSecret: AgBxABesSwEGd4tfBAsysRTE4jy8aSaBZdQJHW3IKc7lT/5jYy4/8h2YpvZFjQJsmlSjufYdC9BIUDsl1z6csfOZEkO+qE8fqZrFaynObWcR163iOSZzfYOPPxZWewCf2pzwZcwbgxn7i9Guk2h94h2I+JCW/sSfUvCnmaJ7ZstMXyABcYgkS8PW/aRBpCEhGlWDWz6AT5UQ/ezHVlpp9FwQMjiIPg3IEVuvYXrJTBdp2dRH6i3r/yoXDixtkhoTgQ1goyfFchjL5m4+U/C3xYZl35jVqaycojTKvpgme02MPCiCKHM+BaC9atflLgtAfTcgnEagtZKXvPrDj+8vlmmyzoYmtHov87RC+b00alN2vxMjtCifGR/hUV9e3KK1kWrLlEjwC/FwJgOigu+lW1Z9XmgPWK6t0E/DFh8icok98Qmy+bFNMqNedh/tgm5l6xcs91vjkDC1O1swfbGr4xG+rlPNW23uvOpUSQN3Dp+kCIL8OyE/jb11EGu4zVZ4C51l/d5DT9035Ux1GFRy/QBv1i7qjzbUlN/CMxPwY4VeTcGAmcgw9pSFeeufCbF7LG1nSZbiQbBkcGi4YiJBcpaOMpGdDrXBQNt6+kmIxZlwzlJIkwP4VkwRSeUbUO06Mij8EI7qNwcgWzdtQZdL13YjmF15zzafynCOS65qgaueqLliu/EHvE9Iediw7EYZSJWZjfH8ikb5kZgsfkqUKcZ/DxGsVS8WaA0uxEIfbw+t/A4ktSLPSgg1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
      name: oidc-azure-clientsecret
      namespace: argocd
    type: Opaque
