---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oidc-azure-clientsecret
  namespace: argocd
spec:
  encryptedData:
    oidc.azure.allowedAudiences: AgBrrN8ZBe/pzXSRXydV3sCpni80FidUZpLQ663yg/DW7jfm2Suvve60Y68BL1pEvDz1+cAxMkf53EiITfwgv799sKgHF9pFGJON7sm/I3hR2G3EtgzT3AuMeEKT1U80CCmjB4t9hbXcIgtwpCWj4sR1EHFBHXbpOMNYsWs9eTStL9TSnyg2SWC9rhicBCU99utjCliZG0AbaCePCSykO5nbV/Ek2YKBgVE+h+2mbUHQlnaP2JYn35aDI5YaDP9Oq1YeMkuHmQ5v5HKgZACu6AxOxHvrkJFurZf36Bs/hY1c8EgoJb68SvzkW0jfjBLHs6zKn0mu3H8vWAzoFmRqK811+VgzgHExLF7fNiTqre1tTTxai5mz98LUAflLCuIqNAp6QqRyGb51RcuJL+tadND/n+BsgZctuSdj0C581ADOEuzIKELGCYz9VzjK2wqQJuzTCX7hBuNpgNCxrOvAW/vnZruKfyJzOTRpmecyD4XvngRe66kJiNhh62rVf7Z4Cj2So1Zv7JPDQEk8tIJt+ltjOu1BqXkGFcpX69LF016JHLZSr1WucXJjXuwwVmUhDnob6U+CIAenXlSFlSIQjH//NEEcXypCAR3PZFfofyGHyWIkJXdSvdXJvMQBAmOqYn9aArCmrNG//yt4UcyLaa1BA0zm9oavZdAi0S3Any0H0Q/foTRPcMrAcbc2HaXlbV1bJ+rBb6aInIaK2PWL3G4qljtS852Ar5Qn8upQv9mb0JCW5pg=
    oidc.azure.clientSecret: AgA6D/OUwiOCip6OF5fOG3AvIbcIQXebjUUO1/Pnu+bf8jEPnD3EKiAHaaDph9V3hlxhHR02w4HZK+vlTpCjvwfOmZuIpC1NiHzs5+WlstDvQ36nnevE63/ZKrDM7Jg93bfa6l1WjlDiyP4oC6tWjv3WJfslk7RHqJPudzqQXXaK3CAiU/jqr5dBd9mVQYfqihAcAsdGQkgCn6MlUlD8cZBFady1ZI1T25QdaGnNWha9SmWeFZKtmjF/2WgppgxDmUlmqxsK22PFU5CAmhYACEuO853RO9r/SPq02B5F/OG4b9wMdb71ZuWpj0QvMgV12XV+OO2+zU9d9zlySjuA6zCCN+SpJhXcaHiCKV/vThkX0ErrVV/N1zxTrSn9Ozd69sLvSMoUYqcyH0JzpX8RChaaCFRr02BlgP9fcvt/UWqyrLrE5VQzQ/UtU86wrg1uyYCrQhqmUGdul/uM1aw+JALSWEZxyFntyrtxBO0scNAWHcz2/Woy74550W7JaZpd+vYWVXEJ9XvhxQ0/akMTAEJLheHYgLWkRujbBELvDZJa6EQ/HXi9S0NIx9ki0l8EfDkp8u9/qnIOpv7RLbSCVH0SCcFvyLfk1SwzVlGxmjHbhzd+uLwig3KZx1XtWA7o8xnStkjb2E1bxZjQkoiP4phmloPdUm5wNCQkprs7KG7xK8EKZ7g+AIUhkP/Bbm4spCkPKksHQLlWLQXBVCQreTp/Hp3Vs4nyPm8pent/93qQ35rmRs3340Dq
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
      name: oidc-azure-clientsecret
      namespace: argocd
    type: Opaque
