---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oidc-azure-clientsecret
  namespace: argocd
spec:
  encryptedData:
    oidc.azure.allowedAudiences: AgBpcwlL89WcYmyu1ijx50DA1hC3iJpRQWBavJBtSsfnSGeyu1gPzezWGGTFfqGUyoQEmwNMAd6a6D+J18OxYte9vDrF9fY3sy9+TzT0RXUyBFKpDXm0NoWOo1pf4j8lZ50M0VTJ/pBdxXWMclTk5V/TfycKfwkf08xYRaq/YZyL1gYElXh8fpGpy09w4TkKEXA2ZEU6KOSNrPuExrvU+jkV/jxVi57MaaNeHeDbRl8y12HizhiiQmpf28pq0P66YyrAOZXHBgTyEmXVRFj+no6F1Iq5iOWOKV6wiJNonJaJa0FXa8MuIyE092FpaJRKZqHWcf0tLXUcZN+vxpDjWMnyvoojcxKCKPvNEtfeytzVFp8PnKQp3JuOit9p3QpuX/3R6Gbv8ol5v8YYlOygPkooe4VuYFRDidkDZw4Em4bCasGGBDlQ9dYmRSxqSLWVS/BJsBLfHF6f7JRt4opKQmT3+G/2jxY6vW0Bu0ezkJGlYYDXcB17l+PxuLSFbzYvKRtVn8TPY9wrzwVenCvlQfQvmMVNwG0aLvYFPJM2j0mKhjpzRHEkLt0xya+pgJh4V6eaDArK4hiVKSlHu+AOIhu8ScmWiw8NPCmqcZUGbcl4ejvwLCTSRHjg5uo8L8sk+wcz3OvLX0sEAI5stxvGzLAJtJ3AfA93YeY961kzLuwwURaqY791z6HqYG4exUnEaDl5y6dy/36ZZSIA9ntIGpMw1PDC+cJKRn3y/jfVQmhJp0pTq78=
    oidc.azure.clientSecret: AgAK6PyIGhIJHoXOdfvGz3HeOoezSVxK9BtYv/5cRcDuCoAHq4xyCjQLWusbdF1aNboy1S+kR9+yJHp/6VfXsOdY3L0vtDSdFhjRvcA68rwtxR14Zeh0wTL9Crx8J9QTNTjrtpeH2qnRDxFQ6832+9p/h348A+a6DFnZl66vE+0Mdug9xEo2kcl3a7h5CWGft0OyBwrWQFJhyNn49kntjJ+OXW7rtd2kUMK1ke4Jz4C8RWWwdbGOc7JdaPrR9/G0krXCWIe8Y23R4j6/pfxJxdD5lnSR1E3cKlODAww+Z7CEDHoSvaVlY9ECEmzC4Z9LCi2EHwIS6PFnaDrcnnMl2Em1WnS3rp9lFjwWMSr+hMjFNbsCS/v7uENydXD8NCWP9NxqkVI12nJkk0BpjVx+ekmRcoKg1fQLgxk9MEGEBtvqVV0lYok+uhVlEb8iQx09oAI7orNMTj+fCSD3iE47B1C9qxW+oI/JRhmk3iML4zUMeCtJZT8BQIBNrvtbCdlRAthxxBBQuTFJ2YDEBmvuKG7YhCEdewL7XlHWaFkwGhUXV+/kvZt1fZf51nrBYVCf2YfTePR4FXR3+5pFpLPJEltKmdWP2dJIvKCkWKBc6cmDleSxbE7BN8Bp44aQrsEYBRRYVH/PuXsBJWqKOu5plozywhALZV8zV+lPjAsoKVzEWcBXqy3DFHZ/ShNhtuCEOf2SyOE4H3s3zcooEVmlJV6mKv3d4n6bJrVauKj0J8BVZHUP7jAi9dPF
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
      name: oidc-azure-clientsecret
      namespace: argocd
    type: Opaque
