apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: user-applications
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - app: drupal-app
            repo: https://github.com/glauciolabs/drupal-app.git
            revision: master
            env: production
            path: k8s/production
          - app: htmly-app
            repo: https://github.com/glauciolabs/htmly-app.git
            revision: HEAD
            env: production
            path: app/production
  template:
    metadata:
      name: '{{app}}-{{env}}'
    spec:
      project: default
      source:
        repoURL: '{{repo}}'
        targetRevision: '{{revision}}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{app}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
