apiVersion: v1
kind: Secret
metadata:
  name: global-github-ssh
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: "https://github.com/glauciolabs"
  githubAppID: ""
  githubAppInstallationID: ""
  githubAppPrivateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    -----END RSA PRIVATE KEY-----
type: Opaque
