apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    chart: contour
    repoURL: "https://projectcontour.github.io/helm-charts/"
    targetRevision: "0.6.0"
    helm:
      values: |
        contour:
          replicaCount: 2
        envoy:
          replicaCount: 2
          service:
            type: LoadBalancer
            externalIPs:
              {{- range .Values.contour.envoy.service.externalIPs }}
              - {{ . | quote }}
              {{- end }}
            nodePorts:
              http: 30080
              https: 30443
  destination:
    server: https://kubernetes.default.svc
    namespace: projectcontour
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /status

