apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    chart: contour
    repoURL: "https://projectcontour.github.io/helm-charts/"
    targetRevision: "0.6.0"
    helm:
      values: |
        contour:
          replicaCount: {{ .Values.contour.contour.replicas }}
        envoy:
          replicaCount: {{ .Values.contour.contour.replicas }}
          service:
            type: {{ .Values.contour.envoy.service.type | quote }}
            nodePorts:
              http: {{ .Values.contour.envoy.service.nodePorts.http }}
              https: {{ .Values.contour.envoy.service.nodePorts.https }}
  destination:
    server: https://kubernetes.default.svc
    namespace: projectcontour
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

