apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    chart: external-dns
    repoURL: "https://kubernetes-sigs.github.io/external-dns/"
    targetRevision: "1.21.1"
    helm:
      values: |
        replicaCount: 2
        replicas: 2
        provider: {{ .Values.externalDns.provider | quote }}
        domainFilters:
          {{- range .Values.externalDns.domainFilters }}
          - {{ . | quote }}
          {{- end }}
        policy: {{ .Values.externalDns.policy | quote }}
        sources:
          {{- range .Values.externalDns.sources }}
          - {{ . | quote }}
          {{- end }}
        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflare-api-token
                key: token
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
