apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    chart: metallb
    repoURL: "https://metallb.github.io/metallb"
    targetRevision: "0.16.1"
    helm:
      values: |
        controller:
          image:
            repository: {{ .Values.metallb.controller.image.repository | quote }}
        speaker:
          image:
            repository: {{ .Values.metallb.speaker.image.repository | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
