# Central values file for K3s HA Infrastructure components

nfsCsi:
  kubeletDir: /var/lib/kubelet

metallb:
  # MetalLB operator/controller values
  controller:
    image:
      repository: quay.io/metallb/controller
  speaker:
    image:
      repository: quay.io/metallb/speaker

# IP Pools configurations
ipPools:
  gcs:
    addresses:
      - 10.20.1.200-10.20.1.250
  gww:
    addresses:
      - 10.30.1.200-10.30.1.250
  h89:
    addresses:
      - 10.10.1.200-10.10.1.250

contour:
  contour:
    replicas: 2
  envoy:
    service:
      type: LoadBalancer
      # Set specific nodePorts for OCI NLB target integration
      nodePorts:
        http: 30080
        https: 30443

certManager:
  installCRDs: true
  replicaCount: 2
  prometheus:
    enabled: false

externalDns:
  provider: cloudflare
  domainFilters:
    - glauciolabs.work
  policy: sync # or upsert-only
  sources:
    - service
    - ingress

cloudflared:
  replicas: 2
  tunnelName: k3s-ha-tunnel
  # The Tunnel ID and Account ID will be resolved from secrets,
  # but we can specify the configurations for the configmap here
  ingress:
    - hostname: "*.glauciolabs.work"
      service: http://envoy.projectcontour.svc.cluster.local:80
    - service: http_status:404
