# Central values file for K3s HA Infrastructure components

nfsCsi:
  kubeletDir: /var/lib/kubelet

contour:
  contour:
    replicas: 2
  envoy:
    service:
      type: LoadBalancer
      # Set specific nodePorts for OCI NLB target integration
      nodePorts:
        http: 30080
        https: 30443
      externalIPs:
        - 100.96.0.5
        - 100.96.0.14
        - 100.96.0.23
        - 100.96.0.20
        - 100.96.0.6
        - 100.96.0.2
        - 100.96.0.17

certManager:
  installCRDs: true
  replicaCount: 2
  prometheus:
    enabled: false

externalDns:
  provider: cloudflare
  domainFilters:
    - glauciolabs.work
  policy: sync # or upsert-only
  sources:
    - service
    - ingress
    - contour-httpproxy

cloudflared:
  replicas: 2
  tunnelName: k3s-ha-tunnel
  # The Tunnel ID and Account ID will be resolved from secrets,
  # but we can specify the configurations for the configmap here
  ingress:
    - hostname: "*.glauciolabs.work"
      service: http://envoy.projectcontour.svc.cluster.local:80
    - service: http_status:404
